name: CI

on:
  pull_request:
    branches:
      - staging*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.changed_files != '*' && github.event.pull_request.changed_files != 'frontend/**'

    steps:
      - name: Skip Build
        run: echo "Skipping build job as changes are not from frontend/** folder"
        continue-on-error: true
