name: Continuous Integration/Deployment

on:
  pull_request:
    branches:
      - main
      - staging
      - develop
      - rc-*
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  frontendCheck:
    name: Check frontend code modified
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "run_job=false" > $GITHUB_OUTPUT
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            if [[ $file == frontend/* ]]; then
              echo "run_job=true" >> $GITHUB_OUTPUT
              break
            fi
          done < files.txt

  build:
    needs: frontendCheck
    if: needs.frontendCheck.outputs.run_job == 'true'
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "THis is the variable we need to print"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - run: echo "::debug::test job"

  deploy:
    runs-on: ubuntu-latest
    needs: frontendCheck
    if: needs.frontendCheck.outputs.run_job == 'false'

    steps:
      - uses: actions/checkout@v3
      - run: echo "::debug::deploy job"

  slack:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - deploy
      - frontendCheck
    if: always()

    steps:
      - run: echo "::debug::deploy job"
